### ISSUE TITLE
'Themosis\Core\Application' not found in functions.php

### ISSUE THREAD

**Issue by N00D13** [themosis/themosis#329] opened 2020-02-28 09:05 UTC
- Themosis Version: 2.0.0
- WordPress Version: 5.3.2
- PHP Version: 7.3.6

### Description
After I have activated the theme I always get the error. I followed the instructions on the website.

`Fatal error: Uncaught Error: Class 'Themosis\Core\Application' not found in C:\xampp\htdocs\wordpress\htdocs\cms\wp-content\themes\hexagon\functions.php:15 Stack trace: #0 C:\xampp\htdocs\wordpress\htdocs\cms\wp-settings.php(497): include() #1 C:\xampp\htdocs\wordpress\htdocs\cms\wp-config.php(90): require_once('C:\\xampp\\htdocs...') #2 C:\xampp\htdocs\wordpress\htdocs\cms\wp-load.php(37): require_once('C:\\xampp\\htdocs...') #3 C:\xampp\htdocs\wordpress\htdocs\cms\wp-blog-header.php(13): require_once('C:\\xampp\\htdocs...') #4 C:\xampp\htdocs\wordpress\htdocs\index.php(11): require('C:\\xampp\\htdocs...') #5 {main} thrown in C:\xampp\htdocs\wordpress\htdocs\cms\wp-content\themes\hexagon\functions.php on line 15`
### Steps to reproduce
After activating the theme comes the error. I have been able to recreate it on my Windows computer as well as on my Mac.

Step one framework installed, then installed the theme and hosted it on Xampp. As soon as I activate the theme, the error comes.

**Comment by jlambe** [comment] 2020-03-25 14:35
Unfortunately I'm not able to reproduce this issue and it doesn't seen to be a code related issue. I'm closing this now but if you're looking for support, you can post your issue in [Gitter](https://gitter.im/themosis/framework) or create an account on our [support service](https://support.themosis.com).

**Closed by jlambe** 2020-03-25 14:35 UTC
