### ISSUE TITLE
Color Picker inside Infinite field causes error in WordPress Editor

### ISSUE THREAD

**Issue by mkhmylife** [themosis/themosis#70] opened 2016-02-20 10:39 UTC
I added a meta box which contains one color picker inside the infinite field. When I go to WordPress Editor and tried to add multiple colors, a javascript error is thrown:
```js
Uncaught TypeError: Cannot read property 'replace' of undefined    //_themosis-core-.js?ver=4.4.2:1291
``` 

My Metabox creation code looks like this:
```php
Metabox::make('Informations', 'projects', ['context'  => 'normal', 'id' => 'page-project-metabox', 'priority' => 'high'])->set([
    Field::text('project-client', ['title' => 'Client']),
    Field::text('project-work', ['title' => 'Range of Work']),
    Field::text('project-location', ['title' => 'Location']),
    
    Field::collection('projects-photos', ['type' => 'Portfolio Images']),
    
	Field::infinite('projects-color-box', [
	    Field::color('colors', ['title' => 'Color Code'])     //This color picker inside an infinite field
	])    
]);
```

**Comment by jlambe** [comment] 2016-02-20 11:10
Indeed there is an issue when we try to add a new row. The JS script can't rename correctly the color field. Will look into this and let you know when the fix is available.

**Comment by jlambe** [comment] 2016-03-09 08:24
@mkhmylife The issue is currently fixed into the `dev-master` branch of the `themosis/framework` repository. You can grab it now or wait for the minor release in one or two days.
Thanks for catching this one.

**Closed by jlambe** 2016-03-09 08:24 UTC
Labels: bug
