### ISSUE TITLE
View composer doesn't get executed for error pages

### ISSUE THREAD

**Issue by KeironLowe** [themosis/themosis#324] opened 2019-11-14 08:37 UTC
- Themosis Version: 2.0.4
- WordPress Version: 5.3
- PHP Version: 7.3.9

### Description
View composers don't seem to get executed for error pages. So I have a view composer which pulls in content for the 404 page, but it never gets executed unless I implicitly set the fallback route to display the 404 view.

### Steps to reproduce
Create view composer for the 404 template, load the page.

### Expected behavior
The view composer should execute

**Comment by jlambe** [comment] 2019-11-14 09:41
Are you using the `Route::get('404', ...)` route ? 

This route is not recommanded as it is a catch-all route from WordPress and may intercept other custom routes endpoints.

You're good to go by using `Route::fallback()` instead and is the recommanded way.

Otherwise if you could post your code so we could also test your scenario.

**Comment by KeironLowe** [comment] 2019-11-14 11:13
No it was the default 404 routing that happens when a set 404 or fallback route doesn't exist.

Slightly related, even with the fallback route set, it appears the view composer doesn't execute if the 404 is set using `abort(404)`.

**Comment by jlambe** [comment] 2019-11-29 09:58
@KeironLowe I've tested the view composer and it is working as expected. Here is the simple test ran:

```php
Route::get('404', function () {
    return view('errors.404');
});

// Inside the app/Providers/AppServiceProvider
// In the "boot()" method
View::composer('errors.404', function ($view) {
    $view->with('test', 42);
});
```

When testing the page, the value `42` is correctly rendered when calling the `$test` variable like so:

```php
<p>{{ $test }}</p>
```

Without your code sample, I can't reproduce the issue so I'm closing this issue.

**Closed by jlambe** 2019-11-29 09:58 UTC

**Comment by KeironLowe** [comment] 2019-11-29 10:06
@jlambe what about the abort(404) part? I'm happy to use the fallback route for my original issue, but it's not correctly executing the the composer when using the abort method.
