### ISSUE TITLE
Extra comma on Ajax Object Breaks IE9 

### ISSUE THREAD

**Issue by maximusblade** [themosis/themosis#104] opened 2016-08-12 16:07 UTC
/themosis-framework/src/Themosis/Ajax/Ajax.php

Install function.

This is the fix.

`public static function install()
	{
		$datas = apply_filters('themosisGlobalObject', array());

        $output = "<script type=\"text/javascript\">\n\r";
        $output.= "//<![CDATA[\n\r";
        $output.= "var ".static::$namespace." = {\n\r";
        $output.= "ajaxurl: '".static::$url."'\n\r";

        if (!empty($datas))
        {
					$output .= ',';
            foreach ($datas as $key => $value)
            {
                $output.= $key.": ".json_encode($value).",\n\r";
            }
        }

        $output.= "};\n\r";
        $output.= "//]]>\n\r";
        $output.= "</script>";

        // Output the datas.
        echo($output);
	}`

**Comment by jlambe** [comment] 2016-08-13 06:00
Will look into this and update it for next release. The issue is probably appearing as well on the admin ajax function then.

**Comment by jlambe** [comment] 2016-10-03 14:48
@maximusblade Can you create a PR against the current framework master branch on the `themosis/framework` repository so I can see the exact change? Thanks

**Comment by jlambe** [comment] 2016-10-25 20:43
Fixed in theme next release.

**Closed by jlambe** 2016-10-25 20:43 UTC

**Comment by maximusblade** [comment] 2016-10-25 21:56
I haven't been able to do this due to lack of time I'm sorry. I hoped my
push would  be sufficient.
